kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: artifactory-storage-pvc
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
spec:
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: artifactory-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi